### ISSUE TITLE
Reset the timer + add 7 days

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/CoutdownClock#4]
## User Story
As a developer, I want the countdown timer to reset itself automatically without me having to adjust the JS code, so that I can do other things that are more important.

### Acceptance
- [ ] When the timer reaches **0** it displays a message for no more than 2 hours.
- [ ] After **2 hours** (can be simulated) the countdown resumes and the date is changed to the following week. 
- [ ] The "following week" is defined as **+7** days to the countdown timer.   
_6 days, 22 hours and some number of minutes_

## Tasks
- [ ] Add the JS to the homepage
- [ ] Get the JS working the way I want it inside a button
- [ ] Add the new js for increment the date
- [ ] add js for showing message for no more than 2 hours
